ptf ~
BEGIN OPTIONS
  SAVE_FLOWS
END OPTIONS
 
BEGIN GRIDDATA
  ICELLTYPE LAYERED
    CONSTANT 1
    CONSTANT 0
    CONSTANT 0
    CONSTANT 0
    CONSTANT 0
  K LAYERED
    OPEN/CLOSE k_aq.ref FACTOR ~    k_aq     ~
    OPEN/CLOSE k_aq.ref FACTOR ~    k_aq     ~
    OPEN/CLOSE k_clay.ref FACTOR ~    k_cl     ~
    OPEN/CLOSE k_aq.ref FACTOR ~    k_aq     ~
    OPEN/CLOSE k_aq.ref FACTOR ~    k_aq     ~
  K33 LAYERED
    OPEN/CLOSE k_aq.ref FACTOR .25000000000
    OPEN/CLOSE k_aq.ref FACTOR .25000000000
    OPEN/CLOSE k_clay.ref IPRN 5
    OPEN/CLOSE k_aq.ref FACTOR .25000000000
    OPEN/CLOSE k_aq.ref FACTOR .25000000000
END GRIDDATA
